stages:
  - stage: A
    displayName: "This job runs on ubuntu."
    pool:
     vmImage: ubuntu-latest
    jobs:
      - job: A
      - job: B
        displayName: "This job runs on windows Machine."
        pool:
         vmImage: windows-latest
    

      


