# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
stages:
  - stage: A
    displayName: "This is job A"
    jobs:
      - job: jobA
  - stage: B
    displayName: "This is job B"
    jobs:
      - job: jobB
      


